<?php

/**
 * @file
 * Contains graph_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

  function graph_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the graph_module module.
    case 'help.page.graph_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generate Dynamic Line and Bar graphs') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function graph_module_theme() {

  return [
    'node__dynamic_graph' => [
      'base hook' => 'node',
    ],
  ];
}
function graph_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'node_dynamic_graph_form'){
    $form['#attached']['library'][] = 'graph_module/dynamic_graph_form_js';
  }
}
function graph_module_preprocess_node(&$variables) {
  //Feed the config settings to the drupal behavior so we can use them in our Javascript

  $line_graph_color = \Drupal::config('graph_module.settings')->get('line_graph_color');
  $variables['#attached'] = [
    'drupalSettings' => [
      'dynamic_graph_js' => [
        'line_graph_color' => $line_graph_color,
      ],
    ],
  ];
}
